spring.application.name=SecurityApplication
spring.datasource.url=jdbc:mysql://localhost:3306/security-app?useSLL=false
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secretKey = your_security key
deploy.env = development


#logging.level.org.springframework.security=DEBUG
#spring.main.allow-bean-definition-overriding=true

#Security Configs
#spring.security.user.name=user
#spring.security.user.password=123

#deploy.env=production


#jwt.secretKey = ayour_security key
